[package]
name = "myfirstrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.10.3"
mnist = {version = "0.5.0", features = ["download"]}
ndarray = "0.15.6"
claim = "0.5.0"